from pathlib import Path

DEFAULT_BASE_URL = "https://ilinkai.weixin.qq.com"
DEFAULT_CDN_BASE_URL = "https://novac2c.cdn.weixin.qq.com/c2c"
DEFAULT_BOT_TYPE = "3"
DEFAULT_APP_ID = "bot"
DEFAULT_CHANNEL_VERSION = "2.1.7"
DEFAULT_STATE_DIR = Path.home() / ".openclaw-weixin-python"

DEFAULT_LONG_POLL_TIMEOUT_S = 35.0
DEFAULT_API_TIMEOUT_S = 15.0
DEFAULT_CONFIG_TIMEOUT_S = 10.0
QR_LONG_POLL_TIMEOUT_S = 35.0
ACTIVE_LOGIN_TTL_S = 5 * 60.0
MAX_QR_REFRESH_COUNT = 3
CDN_UPLOAD_MAX_RETRIES = 3
SESSION_EXPIRED_ERRCODE = -14

MESSAGE_TYPE_BOT = 2
MESSAGE_STATE_FINISH = 2

ITEM_TYPE_TEXT = 1
ITEM_TYPE_IMAGE = 2
ITEM_TYPE_VOICE = 3
ITEM_TYPE_FILE = 4
ITEM_TYPE_VIDEO = 5

UPLOAD_MEDIA_TYPE_IMAGE = 1
UPLOAD_MEDIA_TYPE_VIDEO = 2
UPLOAD_MEDIA_TYPE_FILE = 3
UPLOAD_MEDIA_TYPE_VOICE = 4

TYPING_STATUS_TYPING = 1
TYPING_STATUS_CANCEL = 2
